name: 06 - Contexts
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}
on: 
  push: 
  workflow_dispatch: 
    inputs:
      debug:
        type: boolean
        default: false
        

jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        run: | 
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Object Path on Runner ${{ github.event_path }}"
          echo "full object: " 
          cat "${{ github.event_path }}"
          echo -e "\nRef: ${{ github.ref }}, Ref short name: ${{ github.ref_name }}, Ref Type: ${{ github.ref_type }}"
          echo "Commit SHA: ${{ github.sha }} "
          echo "Actor: ${{ github.actor }}, Actor ID: ${{ github.actor_id }}, Triggering Actor: ${{ github.triggering_actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}, Run #: ${{ github.run_number }}, Run attempt:${{ github.run_attempt }}"
      - name: Retrieve Variable
        run: 
          echo "My repository variable MY_VAR = ${{ vars.MY_VAR }}"

