name: 06 - Contexts
run-name: 06 - Contexts | DEBUG - # ${{ inputs.debug }}
on: 
  push: 
  workflow_dispatch: 
    inputs:
      debug:
        type: boolean
        default: false
env:
  MY_WORKFLOW_VAR: workflow
  MY_OVERWRITTEN_VAR: workflow     

jobs:
  echo-data:
    runs-on: ubuntu-latest
    env: 
      MY_JOB_VAR: job
      MY_OVERWRITTEN_VAR: job
    steps:
      - name: Display Information
        run: | 
          echo "Event Name: ${{ github.event_name }}"
          echo "Event Object Path on Runner ${{ github.event_path }}"
          echo "full object: " 
          cat "${{ github.event_path }}"
          echo -e "\nRef: ${{ github.ref }}, Ref short name: ${{ github.ref_name }}, Ref Type: ${{ github.ref_type }}"
          echo "Commit SHA: ${{ github.sha }} "
          echo "Actor: ${{ github.actor }}, Actor ID: ${{ github.actor_id }}, Triggering Actor: ${{ github.triggering_actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}, Run #: ${{ github.run_number }}, Run attempt:${{ github.run_attempt }}"
      - name: Retrieve Variable
        run: 
          echo "My repository variable MY_VAR = ${{ vars.MY_VAR }}"
      - name: Print Env Variables
        env: 
          MY_OVERWRITTEN_VAR: step
        run: | 
          echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
          echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"
      - name: Print Env Variables 2 
        run: | 
          echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
          echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"
                 

