name: 06 - Contexts

on: 
  push: 
  workflow_dispatch: 

jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        run: | 
          echo "Event Object: ${{ github.event }}, Event Name: ${{ github.event_name }}"
